
// * auth constants
export const REGISTER_START = "REGISTER_START"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const LOGOUT_START = "LOGOUT_START"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILED = "LOGOUT_FAILED"

export const USER_LOGIN = "USER_LOGIN"
export const SET_CREATE_USER = "SET_CREATE_USER"

// * firestore constants

export const GET_POST_START = "GET_POST_START"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILED= "GET_POST_FAILED"

export const SAVE_POST_START = "SAVE_POST_START"
export const SAVE_POST_SUCCESS = "SAVE_POST_SUCCESS"
export const SAVE_POST_FAILED= "SAVE_POST_FAILED"

export const LIKE_POST_START = "LIKE_POST_START"
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"
export const LIKE_POST_FAILED= "LIKE_POST_FAILED"


export const ADD_POST_START = "ADD_POST_START"
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_FAILED= "ADD_POST_FAILED"


export const DELETE_POST_START = "DELETE_POST_START"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAILED= "DELETE_POST_FAILED"

export const REMOVE_LIKED_POST_START= "REMOVE_LIKED_POST_START"
export const REMOVE_LIKED_POST_SUCCESS= "REMOVE_LIKED_POST_SUCCESS"
export const REMOVE_LIKED_POST_FAILED= "REMOVE_LIKED_POST_FAILED"



export const REMOVE_SAVED_POST_START= "REMOVE_SAVED_POST_START"
export const REMOVE_SAVED_POST_SUCCESS= "REMOVE_SAVED_POST_SUCCESS"
export const REMOVE_SAVED_POST_FAILED= "REMOVE_SAVED_POST_FAILED"


export const COMMENT_POST_START = "COMMENT_POST_START"
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS"
export const COMMENT_POST_FAILED = "COMMENT_POST_FAILED"

export const GET_COMMENT_START = "GET_COMMENT_START"
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAILED = "GET_COMMENT_FAILED"


export const DELETE_COMMENT_START = "DELETE_COMMENT_START"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILED = "DELETE_COMMENT_FAILED"


export const SEARCH_START = "SEARCH_START"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_FAILED = "SEARCH_FAILED"